open-edge-insights/uwc

MQTT/docker-compose.yml, build_scripts/02_provision_UWC.sh, build_scripts/03_Build_Run_UWC.sh, build_scripts/06_UnitTestRun.sh, docker-compose_UT.yml, kpi-tactic/Dockerfile, kpi-tactic/Dockerfile_UT, kpi-tactic/docker-compose.yml, modbus-master/Dockerfile, modbus-master/Dockerfile_RTU, modbus-master/Dockerfile_UT, modbus-master/Dockerfile_UT_RTU, modbus-master/modbus_RTU/docker-compose.yml, modbus-master/modbus_TCP/docker-compose.yml, mqtt-bridge/Dockerfile, mqtt-bridge/Dockerfile_UT, mqtt-bridge/docker-compose.yml, sparkplug-bridge/Dockerfile, sparkplug-bridge/Dockerfile_UT, sparkplug-bridge/docker-compose.yml, uwc_common/Dockerfile.common, uwc_common/Dockerfile.common.test, uwc_common/Dockerfile_UT, uwc_common/docker-compose.yml, uwc_recipes/uwc-pipeline-with-kpi-no-sparkplug-bridge.yml, uwc_recipes/uwc-pipeline-with-sparkplug-bridge-no-kpi.yml, uwc_recipes/uwc-pipeline-with-sparkplug-bridge_and_kpi.yml, uwc_recipes/uwc-pipeline-without-sparkplug-bridge.yml
Made some changes in Dockerfile and docker-compose files.
=> uwc: made changes for 2.6 eii rebase

sparkplug-bridge/docker-compose.yml
Removed ports as it not required by sparkplug.
=> sparkplug-bridge: Minnor Update

modbus-master/Modbus-App/include/Common.hpp, modbus-master/Modbus-App/src/ModbusOnDemandHandler.cpp, modbus-master/Modbus-App/src/PeriodicRead.cpp, uwc_common/uwc_util/Src/NetworkInfo.cpp, uwc_common/uwc_util/include/NetworkInfo.hpp
-dataPersist flag is included in JSON payload for Polling update, WOD response and ROD response
Signed-off-by: anuj.kumar@softdel.com <anuj.kumar@softdel.com>
=> uwc/modbus-master/uwc_common: Included dataPersist flag

README.md
Added notes and links for RT patch.
=> README: Modified for RT patch

modbus-master/Modbus-App/src/Main.cpp, modbus-master/Modbus-App/src/PeriodicRead.cpp, modbus-master/Modbus-App/src/PublishJson.cpp, mqtt-bridge/MQTT-Bridge/src/Common.cpp, mqtt-bridge/MQTT-Bridge/src/MQTTPublishHandler.cpp, mqtt-bridge/MQTT-Bridge/src/MQTTSubscribeHandler.cpp, mqtt-bridge/MQTT-Bridge/src/Main.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/include/Metric.hpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/Common.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/InternalMQTTSubscriber.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/Main.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/SCADAHandler.cpp, uwc_common/uwc_util/Src/CommonDataShare.cpp, uwc_common/uwc_util/Src/ConfigManager.cpp, uwc_common/uwc_util/Src/EnvironmentVarHandler.cpp, uwc_common/uwc_util/Src/MQTTPubSubClient.cpp, uwc_common/uwc_util/Src/NetworkInfo.cpp, uwc_common/uwc_util/Src/QueueHandler.cpp, uwc_common/uwc_util/Src/YamlUtil.cpp, uwc_common/uwc_util/Src/ZmqHandler.cpp
-Removed cout statements and added corresponding log messages
Signed-off-by: anuj.kumar@softdel.com <anuj.kumar@softdel.com>
=> uwc:cout removed from all containers

README.md, build_scripts/01_uwc_pre_requisites.sh, build_scripts/02_provision_UWC.sh, eii_configs/service_specific_cfgs/EmbPublisher/UWC_Sample_DB_Publisher_config.json, eii_configs/service_specific_cfgs/EmbPublisher/config.json, uwc_recipes/uwc-pipeline-sample-publisher.yml
Added a database sample publisher for data persist.
=> UWC: Added a Sample Publisher.

build_scripts/02_provision_UWC.sh
Modified 02 script to include the sparkplug prompt messages for 07
recipe file.
=> build_scripts: Added an update for 7 recipe file

docker-compose_UT.yml
Addeed etcd_host in no_proxy for some changes.
=> docker-compose_UT.yml : Modified the docker-compose_UT.yml

build_scripts/02_provision_UWC.sh, build_scripts/2.1_ConfigureScada.sh
uwc/build_scripts : Fix the ESH UI compatibility issues
1. Replace "read -p <string> var_name" with 2 separate "echo & read" statements.
Signed-off-by: nagdeepgk <nagdeep.gk@intel.com>
=> Fix the ESH UI compatibility issues

build_scripts/02_provision_UWC.sh, build_scripts/2.1_ConfigureScada.sh
1. Replace "read -p <string> var_name" with 2 separate "echo & read" statements.
Replica of the earlier PR merged to develop branch.
Signed-off-by: nagdeepgk <nagdeep.gk@intel.com>
=> uwc/build_scripts : Fix the ESH UI compatibility issues

README.md
Readme referring to UG's installation steps
Signed-off-by: nagdeepgk <nagdeep.gk@intel.com>
=> Readme referring to UG's installation steps

build_scripts/02_provision_UWC.sh
1. Update PY version from 3.6 to PY-3 (generic)
Signed-off-by: nagdeepgk <nagdeep.gk@intel.com>
=> [v1.5.1-hotfix]: uwc/build_scripts : Update PY version in script

MQTT/Dockerfile, MQTT/docker-compose.yml, README.md, build_scripts/02_provision_UWC.sh, build_scripts/03_Build_Run_UWC.sh, build_scripts/04_uninstall_UWC.sh, kpi-tactic/Dockerfile, kpi-tactic/docker-compose.yml, modbus-master/Dockerfile, modbus-master/Dockerfile_RTU, modbus-master/modbus_RTU/docker-compose.yml, modbus-master/modbus_TCP/docker-compose.yml, mqtt-bridge/Dockerfile, mqtt-bridge/docker-compose.yml, sparkplug-bridge/Dockerfile, sparkplug-bridge/docker-compose.yml, uwc_common/Dockerfile.common, uwc_common/docker-compose.yml
This PR is a replica from already reviewed & approved PR https://github.com/open-edge-insights/uwc/pull/34.
This new PR was created to get around some of the issues introduced by git.
=> UWC : Changes for multi Stage build

.env, MQTT/docker-compose.yml, docker-compose_UT.yml, kpi-tactic/Dockerfile, kpi-tactic/Dockerfile_UT, kpi-tactic/docker-compose.yml, modbus-master/Dockerfile, modbus-master/Dockerfile_RTU, modbus-master/Dockerfile_UT, modbus-master/Dockerfile_UT_RTU, modbus-master/modbus_RTU/docker-compose.yml, modbus-master/modbus_TCP/docker-compose.yml, mqtt-bridge/Dockerfile, mqtt-bridge/Dockerfile_UT, mqtt-bridge/docker-compose.yml, sparkplug-bridge/Dockerfile, sparkplug-bridge/Dockerfile_UT, sparkplug-bridge/docker-compose.yml, uwc_common/Dockerfile_UT, uwc_common/docker-compose.yml
Earlier containers were referring to EII_VERSION tag modified it to
UWC_VERSION.
=> UWC : Modified the tags of the containers

build_scripts/02_provision_UWC.sh
Added a logic to remove the setenv file in case the 02 is ran again.
=> uwc : Updated 02 script.

kpi-tactic/KPIApp/include/EIIPlBusHandler.hpp, kpi-tactic/KPIApp/src/ControlLoopHandler.cpp, kpi-tactic/KPIApp/src/EIIPlBusHandler.cpp, kpi-tactic/KPIApp/src/KPIAppConfigMgr.cpp, kpi-tactic/KPIApp/src/Main.cpp, kpi-tactic/KPIApp/src/QueueMgr.cpp, kpi-tactic/config.json, kpi-tactic/docker-compose.yml
Modified Kpi to be compatible with new topic format
=> UWC: New_topic update for KPI.

kpi-tactic/LogFileToExcelConverter.py
Added a fix to treat the status code as a integer.
=> kpi-tactic : Minor update for Kpi

.env, Vendor_Apps/EmbPublisher/.dockerignore, Vendor_Apps/EmbPublisher/Dockerfile, Vendor_Apps/EmbPublisher/config.json, Vendor_Apps/EmbPublisher/datafiles/TemplateDef.json, Vendor_Apps/EmbPublisher/datafiles/UWC_Sample_DB_Publisher_config.json, Vendor_Apps/EmbPublisher/docker-compose.yml, Vendor_Apps/EmbPublisher/go.mod, Vendor_Apps/EmbPublisher/pub_tool.go, build_scripts/01_uwc_pre_requisites.sh, build_scripts/05_applyConfigChanges.sh, eii_configs/service_specific_cfgs/EmbPublisher/UWC_Sample_DB_Publisher_config.json, eii_configs/tools-EmbSubscriber.json, modbus-master/Modbus-App/src/ModbusOnDemandHandler.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/include/InternalMQTTSubscriber.hpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/InternalMQTTSubscriber.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/Main.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/SCADAHandler.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/SparkPlugDevMgr.cpp, sparkplug-bridge/config.json, sparkplug-bridge/docker-compose.yml, uwc_common/docker-compose.yml, uwc_common/uwc_util/Src/ConfigManager.cpp, uwc_common/uwc_util/Src/ZmqHandler.cpp, uwc_common/uwc_util/include/ConfigManager.hpp, uwc_common/uwc_util/include/ZmqHandler.hpp, uwc_recipes/uwc-pipeline-with-sparkplug-bridge-no-kpi.yml
Sparkplug changes for porting SP to EMB and new topic format.
=> UWC: update for sparkplug

build_scripts/01_uwc_pre_requisites.sh, eii_configs/service_specific_cfgs/EmbPublisher/UWC_Sample_DB_Publisher_config.json, eii_configs/service_specific_cfgs/EmbPublisher/config.json, kpi-tactic/LogFileToExcelConverter.py
Added the older version of LogFileToExcelConverter.py
and Undo service_specific_cfgs/EmbPublisher removal
=> UWC : Minnor Update

build_scripts/02_provision_build_UWC.sh
Added the step to build cfgmgr agaent in 02 script until the image is
pushed for it.
=> UWC : Config mgr agent update

build_scripts/01_uwc_pre_requisites.sh, build_scripts/02_provision_build_UWC.sh, build_scripts/03_Run_UWC.sh, build_scripts/04_uninstall_UWC.sh
1.) Added Elapsed time for 02 script.
2.) changed Scada occurence to sparkplug
3.) Added fix to remove uwc_data and container logs in 04 script
4.) Added a fix for bug IAPOC9-10682
=> UWC : Updates for build scripts.

.env, build_scripts/2.1_ConfigureScada.sh, kpi-tactic/KPIApp/Test/src/EIIPlBusHandler_ut.cpp, kpi-tactic/KPIApp/include/EIIPlBusHandler.hpp, kpi-tactic/KPIApp/src/EIIPlBusHandler.cpp, kpi-tactic/KPIApp/src/QueueMgr.cpp, modbus-master/Modbus-App/src/ModbusOnDemandHandler.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/include/Common.hpp, sparkplug-bridge/SPARKPLUG-BRIDGE/include/InternalMQTTSubscriber.hpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/Common.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/InternalMQTTSubscriber.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/Main.cpp
1. Improved the sparkplug code in Main.cpp
2. changed EII to EMB in the codebase of sp and kpi
3. Added concept for time stamp for sp
=> uwc: Improvements for sparkplug

build_scripts/02_provision_build_UWC.sh
update for hub. Temporary fix till ETCDUI is available in docker hub registry.
=> UWC : update for hub

MQTT/docker-compose.yml, Vendor_Apps/EmbPublisher/docker-compose.yml, Vendor_Apps/EmbSubscriber/docker-compose.yml, build_scripts/02_provision_build_UWC.sh, build_scripts/2.2_CopyScadaCertsToProvision.sh, uwc_recipes/uwc-pipeline-with-all-modules.yml
1)Updated 02_provision_build_UWC.sh script to include IS_SCADA
2) Added health check for emb pub and sub
3)Added missing kpi use case in recipe 10 
4) Added zmq_broker and influx to 02 script build 
5) Added a fix for mqtt container showing unhealthy 
6) Added a fix in 2.2 script for certs issue 
=> UWC: Bug fixes (health check, recipe 10, 2.2 script for AWS case, other bug fixes).

Vendor_Apps/EmbPublisher/docker-compose.yml, Vendor_Apps/EmbSubscriber/docker-compose.yml, Vendor_Apps/EmbSubscriber/subscriber.go, build_scripts/05_applyConfigChanges.sh
1) Added EmbPub and EmbSub to opensource.
2) Added watch function to EmbSub.
3) Added a fix for AWS issue with Dev mode by coping certs
=> UWC : Added update for EmbPub, EmbSub and AWS Dev mode

build_scripts/02_provision_build_UWC.sh, build_scripts/06_UnitTestRun.sh
Added rm cmd to remove temp dir of previous run
=> UWC: Added a fix for TLS copy issue

.env, MQTT/Dockerfile, Vendor_Apps/EmbPublisher/docker-compose.yml, Vendor_Apps/EmbPublisher/pub_tool.go, Vendor_Apps/EmbSubscriber/docker-compose.yml, Vendor_Apps/README.md, build_scripts/01_uwc_pre_requisites.sh, build_scripts/02_provision_build_UWC.sh, build_scripts/03_Run_UWC.sh, kpi-tactic/Dockerfile, modbus-master/Dockerfile, modbus-master/Dockerfile_RTU, mqtt-bridge/Dockerfile, mqtt-bridge/docker-compose.yml, sparkplug-bridge/Dockerfile, sparkplug-bridge/SPARKPLUG-BRIDGE/src/InternalMQTTSubscriber.cpp, sparkplug-bridge/SPARKPLUG-BRIDGE/src/Main.cpp
1)Made changes according to DBS report
2)Made changes according to klockwork
3)updated 01 script
4)added rm cmd in 02 script
=> UWC : Added fix for scans and changes for rebase

build_scripts/06_UnitTestRun.sh, docker-compose_UT.yml, sparkplug-bridge/SPARKPLUG-BRIDGE/Test/Src/Metric_ut.cpp
=> UWC: Made minor chnages for DBS

MQTT/README-MQTT.md
Comment: The topic 'Steps to set mosquitto version' is not available in this md file.
=> Reviewed and updated README-MQTT.md

.env
=> UWC: Modified uwc env

.env
=> UWC: Modified env

MQTT/README-MQTT.md, README.md, kpi-tactic/README-Kpi-tactics.md, modbus-master/README-modbus-master.md, mqtt-bridge/README-mqtt-bridge.md, sparkplug-bridge/README_sparkplug_bridge.md, uwc_common/README_UWC_Common.md
Updated/Modified the Readmes accordingly.
Signed-off-by: Raj, Kamal <kamal.raj@intel.com>
=> UWC : Changes for READMEs
